# Generated by Django 3.0.5 on 2020-04-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.IntegerField(choices=[(0, 'Primer curso'), (1, 'Segundo curso'), (2, 'Tercero curso'), (3, 'Cuarto curso'), (4, 'Quinto curso')], default=0, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Cursando'), (2, 'Aprobado'), (3, 'Aplazado')], default=0, max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Student')),
            ],
        ),
    ]
