# Generated by Django 3.0.5 on 2020-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Cursando'), (2, 'Aprobado'), (3, 'Aplazado')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='curso',
            field=models.IntegerField(choices=[(0, 'Primer curso'), (1, 'Segundo curso'), (2, 'Tercero curso'), (3, 'Cuarto curso'), (4, 'Quinto curso')], default=0),
        ),
    ]
