# Generated by Django 3.0.5 on 2020-04-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_auto_20200410_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='state',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='student',
        ),
        migrations.AddField(
            model_name='materia',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Cursando'), (2, 'Aprobado'), (3, 'Aplazado')], default=0)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Materia')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Student')),
            ],
        ),
    ]
