# Generated by Django 3.0.5 on 2020-04-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0004_auto_20200410_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'materia')},
        ),
    ]
