# Generated by Django 3.0.5 on 2020-04-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0005_auto_20200410_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='materia.Materia'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='materia.Student'),
        ),
    ]
